build:
  environment:
    php:
      version: '7.3'
  dependencies:
    before:
      - wget -O composer.phar https://getcomposer.org/composer.phar
      - chmod +x composer.phar
      - ./composer.phar install
      - ./tools/phive --no-progress --home ./.phive install --trust-gpg-keys 4AA394086372C20A,31C7E470E2138192,8E730BA25823D8B5,CF1A108D0E7AE720 --force-accept-unsigned
  tests:
    override:
      - command: ./tools/phpunit --coverage-clover=clover.xml
        coverage:
          file:  clover.xml
          format: php-clover
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run
coding_style:
  php:
    spaces:
      around_operators:
        concatenation: true
      ternary_operator:
        in_short_version: false
      other:
        after_type_cast: true

